// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFgxsePXn0k7wGfqzQ6QvGpQHVHowBMTU',
    appId: '1:913689331510:web:ad4ffbc97605b8c6749597',
    messagingSenderId: '913689331510',
    projectId: 'manger-d1123',
    authDomain: 'manger-d1123.firebaseapp.com',
    storageBucket: 'manger-d1123.firebasestorage.app',
    measurementId: 'G-MQE3HXY0VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9F69os0FBXQ0Ey4xaR_gitYc7QQYxIy4',
    appId: '1:913689331510:android:ac18a469c9f538ee749597',
    messagingSenderId: '913689331510',
    projectId: 'manger-d1123',
    storageBucket: 'manger-d1123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFqO0F_THfD1Rd8HwcAApYHRCUzCq8twQ',
    appId: '1:913689331510:ios:355558bbbfcc8f47749597',
    messagingSenderId: '913689331510',
    projectId: 'manger-d1123',
    storageBucket: 'manger-d1123.firebasestorage.app',
    iosBundleId: 'com.example.gmailManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFqO0F_THfD1Rd8HwcAApYHRCUzCq8twQ',
    appId: '1:913689331510:ios:355558bbbfcc8f47749597',
    messagingSenderId: '913689331510',
    projectId: 'manger-d1123',
    storageBucket: 'manger-d1123.firebasestorage.app',
    iosBundleId: 'com.example.gmailManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFgxsePXn0k7wGfqzQ6QvGpQHVHowBMTU',
    appId: '1:913689331510:web:2c965aae5c96b06d749597',
    messagingSenderId: '913689331510',
    projectId: 'manger-d1123',
    authDomain: 'manger-d1123.firebaseapp.com',
    storageBucket: 'manger-d1123.firebasestorage.app',
    measurementId: 'G-2NWFE29YPD',
  );
}
